[package]
name = "cucumber-sort"
version = "0.1.0"
edition = "2024"

[dependencies]
camino = "1.1"

[dev-dependencies]
camino-tempfile = "1.4.1"
cucumber = "0.21"
tokio = { version = "1.0", features = ["fs","macros", "process", "rt"] }
