[package]
name = "cucumber-sort"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
cucumber = "0.21"
tokio = { version = "1.0", features = ["macros", "process", "rt"] }

[[test]]
name = "cuke" # this should be the same as the filename of your test target
harness = false # allows Cucumber to print output instead of libtest
test = false # don't run this as part of "cargo test"
